# Generated by Django 4.2 on 2023-05-07 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_name_alter_group_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'گروه\u200cها', 'verbose_name_plural': 'گروه\u200cها'},
        ),
        migrations.AddField(
            model_name='groupmedias',
            name='file_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='name'),
        ),
    ]
