# Generated by Django 4.2 on 2023-05-06 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.TextField(verbose_name='name')),
                ('level', models.CharField(choices=[(0, 'low'), (1, 'middle'), (2, 'high')], default=0, max_length=1, verbose_name='level')),
                ('description', models.TextField(verbose_name='question desctiption')),
                ('example', models.TextField(verbose_name='question example')),
                ('is_active', models.BooleanField(default=False, verbose_name='is question active')),
            ],
            options={
                'verbose_name': 'questions',
                'verbose_name_plural': 'questions',
            },
        ),
        migrations.CreateModel(
            name='AnswerAtemp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_atemp', to=settings.AUTH_USER_MODEL, verbose_name='group')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_atemp', to='questinos.question', verbose_name='questions')),
            ],
            options={
                'verbose_name': 'AnswerAtemp',
                'verbose_name_plural': 'AnswerAtemp',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('file', models.FileField(upload_to='', verbose_name='file')),
                ('point', models.FloatField(default=0, verbose_name='point')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to=settings.AUTH_USER_MODEL, verbose_name='group')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='questinos.question', verbose_name='questions')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answer',
            },
        ),
    ]
